### ISSUE TITLE
SQL Fehler

### ISSUE THREAD

**Issue by Schmetterlinks** [katjalennartz/MybbRelaPlugin#3]
Ich find dein Plugin total toll - coole Funktionen, aber es gibt ein kleines Problem.
Ich habe dein Plugin erfolgreich installiert und NPCs lassen sich auch eintragen, jedoch scheitert es, wenn ich einen Mitspieler eintragen möchte. Folgende Fehlermeldung kommt:

SQL Error:
    1364 - Field 'r_npcname' doesn't have a default value
Query:
    INSERT INTO mybb_relas (`r_from`,`r_to`,`r_kategorie`,`r_kommentar`,`r_sort`,`r_accepted`,`r_npc`) VALUES (1,2,'Freunde','asdfasdfasdf',1,0,0) 

Ich hab die neueste Version von mybb aktiv: 1.8.27

**Comment by katjalennartz** [comment]
Oh das ist komplett untergegangen. Entschuldige. Ich werd schauen ob ich den Fehler finde und werd ihn beheben. :).

**Comment by katjalennartz** [comment]
i know it's an old issue. sry for not had a look in it.
you need to change the settings of the fields in your database and set an default value.
i've changed the file, so that in future, there will be entered a default value when installing.
